spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anor_booking
    username: anor_user
    password: anor_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB

app:
  jwt:
    secret: ${JWT_SECRET:veryLongAndSecureSecretKeyForJwtTokenGenerationInAnorBookingApp}
    expiration: 86400000  # 24 hours in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
  email:
    from: noreply@anorbooking.com
    base-url: http://localhost:8081
  otp:
    expiration: 300  # 5 minutes in seconds
  file:
    upload-dir: ./uploads

server:
  port: 8081
  servlet:
    context-path: /api
