spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
  email:
    from: ${EMAIL_FROM}
    base-url: ${BASE_URL}
  file:
    upload-dir: ${FILE_UPLOAD_DIR}

logging:
  level:
    com.anor.booking: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
